
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  tags: /tags
  #categories: /categories
  search: /search
  about: https://benenfeng.com
  #rss: /atom.xml

# Miscelaneous
favicon: /logo.png

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#  //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
##- /js/xoxo.js


search:
  path: search.xml
  field: post
  content: true

#RSS feed https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content_limit: 140


sitemap:
    path: sitemap.xml

disqus_shortname: XXX

google_analytics: XXX
baidu_analytics: FuckUBaidu


# switch
show_excerpt: true
show_date: true
#footer
index_page: https://benenfeng.com
main_site: https://benenfeng.com
github: https://github.com/benenfeng
